Orchard.Web/Modules/Orchard.Widgets/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Web.Mvc;
using System.Linq;
using Orchard.ContentManagement;
using Orchard.Core.Contents.Controllers;
using Orchard.DisplayManagement;
using Orchard.Environment.Extensions.Models;
using Orchard.FileSystems.VirtualPath;
using Orchard.Localization;
using Orchard.Logging;
using Orchard.Mvc.Extensions;
using Orchard.Themes.Services;
using Orchard.UI.Admin;
using Orchard.UI.Notify;
using Orchard.Widgets.Models;
using Orchard.Widgets.Services;

namespace Orchard.Widgets.Controllers {

    [ValidateInput(false), Admin]
    public class AdminController : Controller, IUpdateModel {

        private readonly IWidgetsService _widgetsService;
        private readonly ISiteThemeService _siteThemeService;
        private readonly IVirtualPathProvider _virtualPathProvider;

        public AdminController(
            IOrchardServices services,
            IWidgetsService widgetsService,
            IShapeFactory shapeFactory,
            ISiteThemeService siteThemeService,
            IVirtualPathProvider virtualPathProvider) {

            Services = services;
            _widgetsService = widgetsService;
            _siteThemeService = siteThemeService;
            _virtualPathProvider = virtualPathProvider;

            T = NullLocalizer.Instance;
            Logger = NullLogger.Instance;
            Shape = shapeFactory;
        }

        private IOrchardServices Services { get; set; }
        public Localizer T { get; set; }
        public ILogger Logger { get; set; }
        dynamic Shape { get; set; }

        public ActionResult Index(int? layerId) {
            IEnumerable<LayerPart> layers = _widgetsService.GetLayers().ToList();

            if (!layers.Any()) {
                Services.Notifier.Error(T("There are no widget layers defined. A layer will need to be added in order to add widgets to any part of the site."));
                return RedirectToAction("AddLayer");
            }

            LayerPart currentLayer = layerId == null
                ? layers.FirstOrDefault()
                : layers.FirstOrDefault(layer => layer.Id == layerId);

            if (currentLayer == null && layerId != null) { // Incorrect layer id passed
                Services.Notifier.Error(T("Layer not found: {0}", layerId));
                return RedirectToAction("Index");
            }

            ExtensionDescriptor currentTheme = _siteThemeService.GetSiteTheme();
            IEnumerable<string> allZones = _widgetsService.GetZones();
            IEnumerable<string> currentThemesZones = _widgetsService.GetZones(currentTheme);

            string zonePreviewImagePath = string.Format("{0}/{1}/ThemeZonePreview.png", currentTheme.Location, currentTheme.Id);
            string zonePreviewImage = _virtualPathProvider.FileExists(zonePreviewImagePath) ? zonePreviewImagePath : null;

            dynamic viewModel = Shape.ViewModel()
                .CurrentTheme(currentTheme)
                .CurrentLayer(currentLayer)
                .Layers(layers)
                .Widgets(_widgetsService.GetWidgets())
                .Zones(currentThemesZones)
                .OrphanZones(allZones.Except(currentThemesZones))
                .OrphanWidgets(_widgetsService.GetOrphanedWidgets())
                .ZonePreviewImage(zonePreviewImage);

            // Casting to avoid invalid (under medium trust) reflection over the protected View method and force a static invocation.
            return View((object)viewModel);
        }

        [HttpPost, ActionName("Index")]
        public ActionResult IndexWidgetPOST(int widgetId, string returnUrl, int? layerId, string moveUp, string moveDown, string moveHere, string moveOut) {
            if (!string.IsNullOrWhiteSpace(moveOut))
                return DeleteWidget(widgetId, returnUrl);

            if (!IsAuthorizedToManageWidgets())
                return new HttpUnauthorizedResult();

            if (!string.IsNullOrWhiteSpace(moveUp))
                _widgetsService.MoveWidgetUp(widgetId);
            else if (!string.IsNullOrWhiteSpace(moveDown))
                _widgetsService.MoveWidgetDown(widgetId);
            else if (!string.IsNullOrWhiteSpace(moveHere))
                _widgetsService.MoveWidgetToLayer(widgetId, layerId);

            return this.RedirectLocal(returnUrl, () => RedirectToAction("Index"));
        }

        private bool IsAuthorizedToManageWidgets() {
            return Services.Authorizer.Authorize(Permissions.ManageWidgets, T("Not authorized to manage widgets"));
        }


        public ActionResult ChooseWidget(int layerId, string zone, string returnUrl) {
            if (!IsAuthorizedToManageWidgets())
                return new HttpUnauthorizedResult();

            if (string.IsNullOrWhiteSpace(zone)) {
                Services.Notifier.Error(T("Need a zone specified for widget placement."));
                return RedirectToAction("Index");
            }

            IEnumerable<LayerPart> layers = _widgetsService.GetLayers().ToList();

            if (!layers.Any()) {
                Services.Notifier.Error(T("Layer not found: {0}", layerId));
                return RedirectToAction("Index");
            }

            LayerPart currentLayer = layers.FirstOrDefault(layer => layer.Id == layerId);
            if (currentLayer == null) { // Incorrect layer id passed
                Services.Notifier.Error(T("Layer not found: {0}", layerId));
                return RedirectToAction("Index");
            }

            dynamic viewModel = Shape.ViewModel()
                .CurrentLayer(currentLayer)
                .Zone(zone)
                .WidgetTypes(_widgetsService.GetWidgetTypes())
                .ReturnUrl(returnUrl);

            // Casting to avoid invalid (under medium trust) reflection over the protected View method and force a static invocation.
            return View((object)viewModel);
        }

        public ActionResult AddWidget(int layerId, string widgetType, string zone, string returnUrl) {
            if (!IsAuthorizedToManageWidgets())
                return new HttpUnauthorizedResult();

            WidgetPart widgetPart = Services.ContentManager.New<WidgetPart>(widgetType);
            if (widgetPart == null)
                return HttpNotFound();
            try {
                int widgetPosition = _widgetsService.GetWidgets().Count(widget => widget.Zone == widgetPart.Zone) + 1;
                widgetPart.Position = widgetPosition.ToString(CultureInfo.InvariantCulture);
                widgetPart.Zone = zone;
                widgetPart.LayerPart = _widgetsService.GetLayer(layerId);
                dynamic model = Services.ContentManager.BuildEditor(widgetPart);
                // Casting to avoid invalid (under medium trust) reflection over the protected View method and force a static invocation.
                return View((object)model);
            }
            catch (Exception exception) {
                Logger.Error(T("Creating widget failed: {0}", exception.Message).Text);
                Services.Notifier.Error(T("Creating widget failed: {0}", exception.Message));
                return this.RedirectLocal(returnUrl, () => RedirectToAction("Index"));
            }
        }

        [HttpPost, ActionName("AddWidget")]
        public ActionResult AddWidgetPOST(int layerId, string widgetType, string returnUrl) {
            if (!IsAuthorizedToManageWidgets())
                return new HttpUnauthorizedResult();

            WidgetPart widgetPart = _widgetsService.CreateWidget(layerId, widgetType, "", "", "");
            if (widgetPart == null)
                return HttpNotFound();

            var model = Services.ContentManager.UpdateEditor(widgetPart, this);
            try {
                // override the CommonPart's persisting of the current container
                widgetPart.LayerPart = _widgetsService.GetLayer(layerId);
            }
            catch (Exception exception) {
                Logger.Error(T("Creating widget failed: {0}", exception.Message).Text);
                Services.Notifier.Error(T("Creating widget failed: {0}", exception.Message));
                return this.RedirectLocal(returnUrl, () => RedirectToAction("Index"));
            }
            if (!ModelState.IsValid) {
                Services.TransactionManager.Cancel();
                // Casting to avoid invalid (under medium trust) reflection over the protected View method and force a static invocation.
                return View((object)model);
            }

            Services.Notifier.Information(T("Your {0} has been added.", widgetPart.TypeDefinition.DisplayName));

            return this.RedirectLocal(returnUrl, () => RedirectToAction("Index"));
        }

        public ActionResult AddLayer(string name, string description, string layerRule) { // <- hints for a new layer
            if (!IsAuthorizedToManageWidgets())
                return new HttpUnauthorizedResult();

            LayerPart layerPart = Services.ContentManager.New<LayerPart>("Layer");
            if (layerPart == null)
                return HttpNotFound();

            dynamic model = Services.ContentManager.BuildEditor(layerPart);

            // only messing with the hints if they're given
            if (!string.IsNullOrWhiteSpace(name))
                model.Name = name;
            if (!string.IsNullOrWhiteSpace(description))
                model.Description = description;
            if (!string.IsNullOrWhiteSpace(layerRule))
                model.LayerRule = layerRule;

            // Casting to avoid invalid (under medium trust) reflection over the protected View method and force a static invocation.
            return View((object)model);
        }

        [HttpPost, ActionName("AddLayer")]
        public ActionResult AddLayerPOST() {
            if (!IsAuthorizedToManageWidgets())
                return new HttpUnauthorizedResult();

Orchard.Web/Modules/Orchard.Widgets/Views/Widget.ControlWrapper.cshtml
@using Orchard.ContentManagement;
@using Orchard.Widgets;
@if (AuthorizedFor(Permissions.ManageWidgets)) {
    <div class="widget-control">
        <div class="manage-actions">@Html.ItemEditLinkWithReturnUrl(T("Edit").Text, (ContentItem)Model.ContentItem)</div>
    @Display(Model.Child)
    </div>
}
else {
    @Display(Model.Child)
}

Orchard.Web/Modules/Orchard.Widgets/Views/Widget.DeleteButton.cshtml
<fieldset class="delete-button">
    <button type="submit" name="submit.Delete" value="@T("Delete")" itemprop="RemoveUrl">@T("Delete")</button>
</fieldset>

Orchard.Web/Modules/Orchard.Widgets/Views/Widget.Edit.cshtml
<div class="sections">
    <div class="primary">
        @Display(Model.Content)
    </div>
    <div class="secondary">
        @Display(Model.Sidebar)
    </div>
</div>

Orchard.Web/Modules/Orchard.Widgets/Views/Widget.Wrapper.cshtml
@using Orchard.ContentManagement;
@using Orchard.Widgets.Models;
@{
    var widgetPart = ((IContent)Model.ContentItem).As<WidgetPart>();
    var tag = Tag(Model, "article");
}
@tag.StartElement
    @if ( (widgetPart.RenderTitle && HasText(widgetPart.Title)) || Model.Header != null) {
    <header>
        @if ((widgetPart.RenderTitle && HasText(widgetPart.Title))) {
        <h1>@widgetPart.Title</h1>
        }
        @Display(Model.Header)
    </header>
    }
    @Display(Model.Child)
    @if(Model.Footer != null) {
    <footer>
        @Display(Model.Footer)
    </footer>
    }
@tag.EndElement

Orchard.Web/Modules/Orchard.Widgets/Views/Widget.cshtml
@Display(Model.Content)

Orchard.Web/Modules/Orchard.Widgets/Views/WidgetLayerVisibility.cshtml
@using Orchard.Widgets.Models;
@{
    Style.Require("WidgetsAdmin");
    Script.Require("jQuery");
    IEnumerable<LayerPart> layers = Model.Layers;
}
@functions {
    static string EncodeLineBreaks(string text) {
		if (!String.IsNullOrEmpty(text)){
			return text.Replace(Environment.NewLine, "\\\\n");
		}
	
		return text;
    }
}
<script type="text/javascript">
//<![CDATA[
    document.write("<div id=\"widgets-layer-visibility\"><h3>@T("All Layers:")</h3></div>");
//]]>
</script>
@using(Script.Foot()) {
<script type="text/javascript">
//<![CDATA[
    (function ($) {
        var currentLayerId = @Model.CurrentLayer.Id;
        var layers = [
        @foreach (var layer in layers) {
            <text>{"name":"@layer.Name","description":"@EncodeLineBreaks(layer.Description)","id":@layer.Id}@(layer != layers.Last() ? "," : "")</text>
        }
        ];
        var visWrapper = $("#widgets-layer-visibility");
        var visContainer = $("<ul></ul>");
    
        var widgetPlacement = $("#widgets-zones");
        for (var i = 0; i < layers.length; i++) {
            var layersWidgets = widgetPlacement.find(".widgets-layer-" + layers[i].id);
            var layer = "";

            if (layersWidgets.length > 0) {
                layer = $("<li title=\"" + layers[i].description + "\" class=\"widgets-" + ((layers[i].id == currentLayerId && "this") || "other") + "-layer\">" + layers[i].name + "</li>");
                layer.data("widgets", layersWidgets);
                layersWidgets.each(function(){
                    $(this).data("widgets-vis-control", layer);
                });
            }
            else {
                layer = $("<li title=\"" + layers[i].description + "\" class=\"widgets-empty-layer" + ((layers[i].id == currentLayerId && " widgets-this-layer") || "") + "\">" + layers[i].name + " <span>[empty]</span></li>");
            }

            visContainer.append(layer);
        }

        $("#widgets-layer-visibility .widgets-other-layer").live("click", function() {
            var _this = $(this);
            _this.toggleClass("off");
            if (_this.hasClass("off")) {
                _this.data("widgets").hide();
            }
            else {
                _this.data("widgets").show();
            }
        });
        $("#widgets-layer-visibility .widgets-other-layer").live("hover", function() {
            $(this).data("widgets").toggleClass("on");
        });
        $("#widgets-zones .widgets-other-layer").live("hover", function() {
            var layer = $(this).data("widgets-vis-control");
            layer.toggleClass("on");
            layer.data("widgets").toggleClass("on");
        });

        visWrapper.append(visContainer);
    })(jQuery);
//]]>
</script>
}

Orchard.Web/Modules/Orchard.Widgets/Views/WidgetLayersControl.cshtml
@using Orchard.Utility.Extensions;
@using Orchard.Widgets.Models;
@{
    Style.Require("WidgetsAdmin");
    Script.Require("Switchable");
    Style.Require("Switchable");
    IEnumerable<LayerPart> layers = Model.Layers;
    var returnUrl = Request.RawUrl;
}
<div id="widgets-layers-control" class="widgets-container">
    @if (layers.Any()) {
        using (Html.BeginForm("index", "admin", FormMethod.Get, new {area = "Orchard.Widgets"})) {
            <fieldset class="bulk-actions-auto">
                <label for="layerId">@T("Current Layer:")</label>
                <select id="layerId" name="layerId">
                    @foreach (var layer in layers) {
                        @Html.SelectOption((int)Model.CurrentLayer.Id, (int)layer.Id, (string)layer.Name)
                    }
                </select>
                <button type="submit" class="apply-bulk-actions-auto">@T("Show")</button>
                @Html.Link(T("Edit").Text, Url.Action("EditLayer", "Admin", new { area = "Orchard.Widgets", id = Model.CurrentLayer.Id, returnUrl }), new { @class = "button" })
            </fieldset>
        }
    }
    <div id="widgets-layer-add">
        @Html.Link(T("Add a new layer...").Text, Url.Action("AddLayer", "Admin", new { area = "Orchard.Widgets", returnUrl }))
    </div>
    
    @if (!String.IsNullOrEmpty(Model.CurrentLayer.Description)) {
        <div>
            <span class="hint" id="widgets-layer-description">@Model.CurrentLayer.Description</span>
            <br />
        </div>
    }
</div>

Orchard.Web/Modules/Orchard.Widgets/Views/WidgetPlacement.Orphans.cshtml
@using Orchard.Utility.Extensions;
@using Orchard.Widgets.Models;
@{
    Style.Require("WidgetsAdmin");
    IEnumerable<WidgetPart> widgets = Model.OrphanWidgets;
    var returnUrl = Request.RawUrl;
}
@if (widgets.Count() > 0) {
<div id="widgets-orphans" class="widgets-container widgets-listed message-Warning">
    <h3>@T("Widgets with problems.")</h3>
    <p>@T("These widgets aren't going to appear anywhere because they're missing the CommonPart from their content type. To fix these widgets, if you still want to keep them around, start by fixing their <a href=\"{0}\">Content Types</a>.", Url.Action("Index", "Admin", new { area = "Orchard.ContentTypes" }))</p>
    <ul>
        @foreach (WidgetPart widget in widgets) {
            <li class="@(widget == widgets.First() ? "first" : (widget == widgets.Last() ? "last" : ""))">
                @using (Html.BeginFormAntiForgeryPost()) {
                    <h3>@Html.ActionLink(HasText(widget.Title) ? widget.Title : widget.TypeDefinition.DisplayName, "EditWidget", new { @widget.Id, returnUrl })</h3>
                    <div class="widgets-actions">
                        <button name="moveOut" class="link" type="submit" value="1" itemprop="RemoveUrl">@T("Remove")</button>
                    </div>
                    @Html.Hidden("widgetId", widget.Id)
                    @Html.Hidden("returnUrl", returnUrl)
                }
            </li>
        }
    </ul>
</div>
}

Orchard.Web/Modules/Orchard.Widgets/Views/WidgetPlacement.Zones.cshtml
@using Orchard.Utility.Extensions;
@using Orchard.Widgets.Models;
@{
    Style.Require("WidgetsAdmin");
    IEnumerable<WidgetPart> widgets = Model.Widgets;
    IEnumerable<string> zones = Model.Zones;
    var returnUrl = Request.RawUrl;
}
<ol>
    @foreach (string zone in zones) {
        int count = widgets.Where(w => w.Zone == zone).Count();
        MvcHtmlString classAttr = null;
        if (count == 0) {
            classAttr = new MvcHtmlString(" class=\"widgets-none\"");
        }
        <li@(classAttr)>
            <h2>@zone</h2>
            <div class="widgets-actions">@Html.ActionLink(T("Add").Text, "ChooseWidget", new { layerId = Model.CurrentLayer.Id, zone, returnUrl }, new { @class = "button grey" })</div>
            <ul class="widgets-zone-widgets">
                @if (count > 0) {
                    int i = 0;
                    foreach (WidgetPart widget in widgets.Where(w => w.Zone == zone).OrderBy(w => w.Position, new Orchard.UI.FlatPositionComparer())) {
                        <li class="widgets-@(widget.LayerId == Model.CurrentLayer.Id ? "this" : "other")-layer widgets-layer-@widget.LayerId@(i == 0 ? " first" : (i == count ? " last" : ""))">
                            @using (Html.BeginFormAntiForgeryPost()) {
                                <h3>@Html.ActionLink(HasText(widget.Title) ? widget.Title : widget.TypeDefinition.DisplayName, "EditWidget", new { @widget.Id, returnUrl })</h3>
                                <div class="widgets-actions">
                                    @if (widget.LayerId != Model.CurrentLayer.Id) {
                                    <button name="moveHere" class="link" type="submit" value="1">@T("Move to current layer")</button>
                                    }
                                    else { /* it could be useful to remove the widget regardless of the layer it's on but there's no place in the current UI for this and "Move to current layer" */
                                    <button name="moveOut" class="link" type="submit" value="1" itemprop="RemoveUrl">@T("Remove")</button>
                                    }
                                </div>
                                <div class="widgets-move-somewhere">
                                    <button name="moveUp" @(new MvcHtmlString(i == 0 ? "disabled='disabled'" : "")) class="widgets-move widgets-move-up" type="submit" title="@T("Move up")" value="1">@T("Move up")</button>
                                    <button name="moveDown" @(new MvcHtmlString(++i == count ? "disabled='disabled'" : "")) class="widgets-move widgets-move-down" type="submit" title="@T("Move down")" value="1">@T("Move down")</button>
                                </div>
                                @Html.Hidden("widgetId", widget.Id)
                                @Html.Hidden("returnUrl", returnUrl)
                            }
                       </li>
                    }
                }
            </ul>
        </li>
    }
</ol>

Orchard.Web/Modules/Orchard.Widgets/Views/WidgetPlacement.cshtml
@using Orchard.Utility.Extensions;
@using Orchard.Widgets.Models;
@{
    Style.Require("WidgetsAdmin");
    IEnumerable<WidgetPart> widgets = Model.Widgets;
    IEnumerable<string> zones = Model.Zones;
    IEnumerable<string> orphanZones = Model.OrphanZones;
    var returnUrl = Request.RawUrl;
}
<div id="widgets-placement">
    <div id="widgets-layers" class="widgets-container detail-view switchable">
        <div id="widgets-zones" class="widgets-listed">
            @Display.WidgetPlacement_Zones(Widgets: Model.Widgets, Zones: Model.Zones, CurrentLayer: Model.CurrentLayer)
        </div>
        @if (orphanZones.Count() > 0) {
            <div id="widgets-zones-orphans-container">
                <h3>@T("Zones for other enabled themes.")</h3>
                <p>@T("Widgets in these zones will not appear anywhere when your currently active theme is applied. They might still appear in selectively applied (e.g. mobile) themes.")</p>
                <div id="widgets-zones-orphans" class="widgets-listed">
                    @Display.WidgetPlacement_Zones(Widgets: Model.Widgets, Zones: Model.OrphanZones, CurrentLayer: Model.CurrentLayer)
                </div>
            </div>
        }
    </div> 
</div>

Orchard.Web/Modules/Orchard.Widgets/Views/WidgetSimplePreview.cshtml
@using Orchard.Environment.Extensions.Models
@if (HasText(Model.ZonePreviewImage)) {
<p id="widgets-theme-zone-preview">@Html.Image(Href((string)Model.ZonePreviewImage), T("{0} zone preview", (string)Model.CurrentTheme.Name).Text, null)</p>
}